#!/bin/bash -e

command_name=$1
command_args=${@:2}

run() {
  args=${@:1}
  docker-compose run --rm web $args
}

case $command_name in
  setup)
    docker-compose build --build-arg uid=$EUID
    run bundle install
    ;;
  bash)
    run bash
    ;;
  bundle)
    run bundle install
    ;;
  bash)
    run /bin/bash
    ;;
  rspec)
    run bundle exec rspec
    ;;
  usage)
    echo -e "Usage:\n"
    ;;
  *)
    $0 usage
  ;;
esac
